# syntax=docker/dockerfile:1
ARG BUILDKIT_SBOM_SCAN_CONTEXT=true
ARG BUILDKIT_SBOM_SCAN_STAGE=builder

FROM --platform=${BUILDPLATFORM:-linux/amd64} golang:1.23 AS builder

ARG TARGETPLATFORM
ARG BUILDPLATFORM
ARG TARGETOS
ARG TARGETARCH

COPY ./ /build
WORKDIR /build

RUN go mod verify && \
    GOOS=${TARGETOS} GOARCH=${TARGETARCH} CGO_ENABLED=0 go build -o /prom-label-proxy

FROM quay.io/prometheus/busybox-${TARGETOS}-${TARGETARCH}:glibc

COPY --from=builder prom-label-proxy /bin/prom-label-proxy

LABEL org.opencontainers.image.title="Qdrant Cloud Monitor"
LABEL org.opencontainers.image.description="Qdrant Cloud Monitor for metrics"
LABEL org.opencontainers.image.url="https://qdrant.com/"
LABEL org.opencontainers.image.documentation="https://qdrant.com/docs"
LABEL org.opencontainers.image.source="https://github.com/qdrant/qdrant-cloud-monitor"
LABEL org.opencontainers.image.vendor="Qdrant"

USER nobody

ENTRYPOINT ["/bin/prom-label-proxy"]
