{{- if .Values.kubeRBACProxy.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "prom-label-proxy.labels" . | nindent 4 }}
  name: {{ template "prom-label-proxy.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "prom-label-proxy.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "prom-label-proxy.serviceAccountName" . }}
  namespace: {{ template "prom-label-proxy.namespace" . }}
{{- end -}}
